version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: .ops/docker/php/Dockerfile
    container_name: app
    environment:
      DATABASE_MYSQL_HOST: db_mysql
      DATABASE_MYSQL_PORT: 3306
      DATABASE_MYSQL_USERNAME: user
      DATABASE_MYSQL_PASSWORD: password
      DATABASE_MYSQL_DATABASE: database
    depends_on:
      - db_mysql
    volumes:
      - .:/var/www

  db_mysql:
    image: mysql:8.0
    container_name: db_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: database
    ports:
      - "3306:3306"